//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimeMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commodity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Commodity()
        {
            this.Carts = new HashSet<Cart>();
            this.CommodityImages = new HashSet<CommodityImage>();
            this.CommodityRatings = new HashSet<CommodityRating>();
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public decimal CommodityId { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public Nullable<decimal> SubCategoryId { get; set; }
        public string SellerId { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<byte> PriceUnitId { get; set; }
        public string PriceNote { get; set; }
        public bool Available { get; set; }
        public bool Publish { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public bool IsFeatured { get; set; }
        public Nullable<double> OriginalPrice { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> Rating { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommodityImage> CommodityImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommodityRating> CommodityRatings { get; set; }
        public virtual PriceUnit PriceUnit { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }

        public Nullable<decimal> CategoryId { get; set; }
        public virtual Category Category { get; set; }
    }
}
