//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimeMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public decimal OrderId { get; set; }
        public Nullable<decimal> OrderStatusId { get; set; }
        public string CustomerId { get; set; }
        public string SellerId { get; set; }
        public Nullable<decimal> CommodityId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string Notes { get; set; }
        public Nullable<int> SellerRating { get; set; }
        public Nullable<int> CustomerRating { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual Commodity Commodity { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
    }
}
