
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PrimeMarket.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Order
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Order()
    {

        this.OrderItems = new HashSet<OrderItem>();

    }


    public decimal OrderId { get; set; }

    public Nullable<byte> OrderStatusId { get; set; }

    public string CustomerId { get; set; }

    public Nullable<System.DateTime> RequestDate { get; set; }

    public Nullable<System.DateTime> CancelDate { get; set; }

    public string Notes { get; set; }

    public Nullable<double> Total { get; set; }

    public Nullable<byte> PaymentMethodId { get; set; }

    public bool isPaid { get; set; }



    public virtual AspNetUser AspNetUser { get; set; }

    public virtual OrderStatu OrderStatu { get; set; }

    public virtual PaymentMethod PaymentMethod { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OrderItem> OrderItems { get; set; }

}

}
