

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PrimeMarket.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class PrimeMarketEntities : DbContext
{
    public PrimeMarketEntities()
        : base("name=PrimeMarketEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<AspNetRole> AspNetRoles { get; set; }

    public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }

    public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }

    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }

    public virtual DbSet<Cart> Carts { get; set; }

    public virtual DbSet<CartStatu> CartStatus { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Commodity> Commodities { get; set; }

    public virtual DbSet<CommodityImage> CommodityImages { get; set; }

    public virtual DbSet<CommodityRating> CommodityRatings { get; set; }

    public virtual DbSet<District> Districts { get; set; }

    public virtual DbSet<Governorate> Governorates { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderItem> OrderItems { get; set; }

    public virtual DbSet<OrderStatu> OrderStatus { get; set; }

    public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }

    public virtual DbSet<PriceUnit> PriceUnits { get; set; }

    public virtual DbSet<SubCategory> SubCategories { get; set; }

    public virtual DbSet<UserRating> UserRatings { get; set; }

    public virtual DbSet<Village> Villages { get; set; }

    public virtual DbSet<View_Cart> View_Cart { get; set; }

    public virtual DbSet<View_Commodity> View_Commodity { get; set; }


    public virtual ObjectResult<Nullable<int>> SP_Commodity_Count(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
    {

        var startDateParameter = startDate.HasValue ?
            new ObjectParameter("StartDate", startDate) :
            new ObjectParameter("StartDate", typeof(System.DateTime));


        var endDateParameter = endDate.HasValue ?
            new ObjectParameter("EndDate", endDate) :
            new ObjectParameter("EndDate", typeof(System.DateTime));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_Commodity_Count", startDateParameter, endDateParameter);
    }

}

}

