//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimeMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowCommodity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShowCommodity()
        {
            this.Carts = new HashSet<Cart>();
            this.Orders = new HashSet<Order>();
        }
    
        public decimal ShowCommodityId { get; set; }
        public string Title { get; set; }
        public string Details { get; set; }
        public Nullable<decimal> SubCategoryId { get; set; }
        public Nullable<decimal> SellerId { get; set; }
        public Nullable<double> Price { get; set; }
        public string PriceNote { get; set; }
        public string ImagePath { get; set; }
        public bool Available { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual Account Account { get; set; }
    }
}
