//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimeMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubSubCategory
    {
        public decimal SubSubCategoryId { get; set; }
        public string SubSubCategory1 { get; set; }
        public Nullable<decimal> SubCategoryId { get; set; }
        public string ImagePath { get; set; }
    
        public virtual SubCategory SubCategory { get; set; }
    }
}
