
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace PrimeMarket.Models
{

using System;
    using System.Collections.Generic;
    
public partial class UserRating
{

    public decimal UserRatingId { get; set; }

    public string ReviewerId { get; set; }

    public string UserId { get; set; }

    public Nullable<byte> Rating { get; set; }

    public string Comment { get; set; }

}

}
